hidden_units_1: 512  
hidden_units_2: 256  
hidden_units_3: 128  
hidden_units_4: 64  
dropout_rate: 0.5   
learning_rate: 0.0003 
batch_size: 128   
epochs: 30     
train_split: 0.8
save_threshold: 0.5