architecture: CNN  # Choices: CNN, MLP, Transformer

# CNN Configuration
conv_channels_1: 64
conv_channels_2: 128
conv_channels_3: 256
conv_channels_4: 512
conv_channels_5: 1024
linear_layer_1: 512
linear_layer_2: 256
dropout_rate: 0.3

# MLP Configuration
hidden_units_1: 4096
hidden_units_2: 2048
hidden_units_3: 1024
hidden_units_4: 512
hidden_units_5: 256
hidden_units_6: 128
hidden_units_7: 64
mlp_dropout_rate: 0.1

# Transformer Configuration
num_heads: 2
num_layers: 2
hidden_dim: 512
dropout_rate: 0.3

# General Configuration
learning_rate: 0.0005
batch_size: 256
epochs: 100
train_split: 0.8
save_threshold: 0.5